version: "3.9"
services:

  nginx:
    container_name: nginx
    image: bitnami/nginx:latest
    tty: true
    ports:
      - 80:8080
    #env_file:
    #  - ./nginx/env/nginx.env 
    volumes:
      # nesta pasta que os sites vão ficar
      - ~/workspace/www/sites:/app

      # exemplo carregando apenas um arquivo
      # - ./nginx/config/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf
      
      # exemplo carregando uma pasta inteira de configurações
      - ./nginx/config:/opt/bitnami/nginx/conf/server_blocks

    #depends_on:

    networks:
      - dsi_server

networks:
  dsi_server:
    driver: bridge
